apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo
data:
  PORT: "8080"
  MONGO_URI: "mongodb://mongodb:27017/much_todo_db"
  DB_NAME: "much_todo_db"
  JWT_EXPIRATION_HOURS: "72"
  ENABLE_CACHE: "false"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "text"
